name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on:
      - codebuild-ManualAuto-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Run your build steps
      run: |
        # Your build commands go here
        echo "Building with CodeBuild GH Actions here"
        # Add more build steps as needed here

