name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-TestCodeHub-${{ github.run_id }}-${{ github.run_attempt }}
      - image:${{ matrix.os }}
      - instance-size:${{ matrix.size }}
      - fleet:myFleet
      - buildspec-override:false
    strategy:
      matrix:
        include:
          - os: arm-3.0
            size: small
          - os: al2-5.0
            size: large
    steps:
      - run: echo "Hello World!"
